FROM node:20-alpine 
 
WORKDIR /app

COPY react-intro/package*.json ./

RUN npm install

RUN chown -R node:node /app/node_modules

COPY react-intro/ ./

RUN chown -R node:node /app

USER node

ENV BROWSER=none
ENV ESLINT_NO_DEV_ERRORS=true
 
EXPOSE 3000

CMD ["npm", "start"]
